language: java
dist: trusty

env:
  - MVN="mvn --settings ${TRAVIS_BUILD_DIR}/.travis.settings.xml"

addons:
  sonarcloud:
    organization: retest
    token:
      secure: "${SONAR_CLOUD_TOKEN}"

notifications:
  email: false

cache:
  directories:
    - "${HOME}/.sonar/cache/"
    - "${HOME}/.m2/"

install: true

script:
  - ${MVN} clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar

deploy:
  - provider: releases
    api_key: "${GH_TOKEN}"
    file_glob: true
    file: "./target/recheck-cli-*-bin.zip"
    skip_cleanup: true
    draft: true
    on:
      tags: true
