language: java
dist: trusty

notifications:
  email: false

cache:
  directories:
    - "${HOME}/.m2/"

before_install:
  # copy Maven settings
  - cp .travis.settings.xml ${HOME}/.m2/settings.xml

install: true
