language: java
dist: trusty

addons:
  sonarcloud:
    organization: retest
    token:
      secure: "${SONAR_CLOUD_TOKEN}"

notifications:
  email: false

cache:
  directories:
    - "${HOME}/.sonar/cache/"
    - "${HOME}/.m2/"

install: true

script: ci/script.sh

deploy:
  - provider: releases
    api_key: "${GH_TOKEN}"
    file_glob: true
    file: "./target/recheck-cli-*-bin.zip"
    skip_cleanup: true
    draft: true
    on:
      tags: true
