version: 1
update_configs:
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "daily"
    default_reviewers:
      - "martin-v"
      - "diba1013"
      - "githubert"
    ignored_updates:
      - match:
          # We update these manually within the release process
          dependency_name: "de.retest:recheck*"
